apiVersion: v1
kind: Service
metadata:
  name: {{ include "mepchart.fullname" . }}
  labels:
    {{- include "mepchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mep.internalPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mepchart.selectorLabels" . | nindent 4 }}
